services:
  catalogdb:
    image: mongo:latest
  
  basketdb:
    image: redis:alpine
  
  discountdb:
    image: postgres:alpine
  
  catalog.api:
    image: ghcr.io/hardingadonis/dotnet-microservices-catalog.api:latest
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb
  
  basket.api:
    image: ghcr.io/hardingadonis/dotnet-microservices-basket.api:latest
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdb
  
  discount.api:
    image: ghcr.io/hardingadonis/dotnet-microservices-discount.api:latest
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
    depends_on:
      - discountdb
  
  portainer:
    image: portainer/portainer-ce:alpine-sts