services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8081:8081"

volumes:
  mongo_data:
