services:
  catalogdb:
    image: mongo:latest
  
  basketdb:
    image: redis:latest
  
  catalog.api:
    image: ghcr.io/hardingadonis/dotnet-microservices-catalog.api:latest
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb
  
  basket.api:
    image: ghcr.io/hardingadonis/basket.api:latest
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdb