name: PR validation

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  if_new_pr:
    name: PR validation
    if: github.head_ref != 'develop'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            await (async () => {
              let message = "";

              message.push("Hi! You've opened a PR to the `main` branch.\n");
              message.push("Please target the `develop` branch for future PRs.\n");
              message.push(`Thanks! @${context.actor}`);

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message.join('\n'),
              });
            });
