name: Publish Discount service image

on:
  push:
    branches:
      - main
    paths:
      - src/Services/Discount/**

jobs:
  publish:
    name: Publish Discount service image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          chmod +x ./scripts/get_version.sh
          echo "version=$(./scripts/get_version.sh 3)" >> $GITHUB_OUTPUT

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish discount.api image
        run: |
          cp ./src/Services/Discount/Discount.API/Dockerfile .
          docker buildx build . \
            -t ghcr.io/${{ github.repository_owner }}/dotnet-microservices-discount.api:${{ steps.get_version.outputs.version }} \
            -t ghcr.io/${{ github.repository_owner }}/dotnet-microservices-discount.api:latest \
            --platform=linux/amd64 \
            --load
          docker push ghcr.io/${{ github.repository_owner }}/dotnet-microservices-discount.api:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/dotnet-microservices-discount.api:latest